1)...
CREATE TABLE EMPLOYEEE1(
   EMP_ID INT PRIMARY KEY,
   EMP_NAME VARCHAR(50),
   EMP_SAL INT,
   DEPT_NO INT,
   L_NAME VARCHAR(10),
   DEPT_NAME VARCHAR(20),
   JOB_ID VARCHAR(15),
   HIREDATE DATE
);

INSERT INTO EMPLOYEEE1(EMP_ID, EMP_NAME, EMP_SAL, DEPT_NO, L_NAME, DEPT_NAME, JOB_ID, HIREDATE)
VALUES ('101', 'SMITH', '800', '20', 'SHAH', 'MACHINE LEARNING', 'FI_MGR', '09-MAR-96')

INSERT INTO EMPLOYEEE1(EMP_ID, EMP_NAME, EMP_SAL, DEPT_NO, L_NAME, DEPT_NAME, JOB_ID, HIREDATE)
VALUES ('102', 'SNEHAL', '1600', '25', 'GUPTA', 'DATA SCIENCE', 'LEC', '14-MAR-96')

INSERT INTO EMPLOYEEE1(EMP_ID, EMP_NAME, EMP_SAL, DEPT_NO, L_NAME, DEPT_NAME, JOB_ID, HIREDATE)
VALUES ('103', 'ADAMA', '1100', '20', 'WALES', 'MACHINE LEARNING', 'MK_MGR', '30-NOV-95')

INSERT INTO EMPLOYEEE1(EMP_ID, EMP_NAME, EMP_SAL, DEPT_NO, L_NAME, DEPT_NAME, JOB_ID, HIREDATE)
VALUES ('104', 'AMAN', '3000', '15', 'SHARMA', 'VIRTUAL REALITY', 'COMP_OP', '02-OCT-97')

INSERT INTO EMPLOYEEE1(EMP_ID, EMP_NAME, EMP_SAL, DEPT_NO, L_NAME, DEPT_NAME, JOB_ID, HIREDATE)
VALUES ('105', 'ANITA', '50000', '10', 'PATEL', 'BIG DATA ANALYTICS', 'COMP_OP', '01-JAN-96')

INSERT INTO EMPLOYEEE1(EMP_ID, EMP_NAME, EMP_SAL, DEPT_NO, L_NAME, DEPT_NAME, JOB_ID, HIREDATE)
VALUES ('106', 'SNEHA', '2450', '10', 'JOSHEPH', 'BIG DATA ANALYTICS', 'FI_ACC', '26-SEP-97')

INSERT INTO EMPLOYEEE1(EMP_ID, EMP_NAME, EMP_SAL, DEPT_NO, L_NAME, DEPT_NAME, JOB_ID, HIREDATE)
VALUES ('107', 'ANAMIKA', '2975', '30', 'JHA', 'CYBER SECURITY', 'IT_PROG', '01-JUL-97')

SELECT * FROM EMPLOYEEE1

UPDATE EMPLOYEEE1 SET EMP_NAME = 'ROHIL' , EMP_SAL = '100000' WHERE DEPT_NO = '25'; 

DELETE FROM EMPLOYEEE1 WHERE EMP_SAL = '2975';

SELECT COUNT(EMP_SAL) FROM EMPLOYEEE1;

SELECT SUM(EMP_SAL) FROM EMPLOYEEE1;

SELECT AVG(EMP_SAL) FROM EMPLOYEEE1;

SELECT MIN(EMP_SAL) FROM EMPLOYEEE1;

SELECT MAX(EMP_SAL) FROM EMPLOYEEE1;

ALTER TABLE EMPLOYEEE1 ADD EMAIL VARCHAR(255);

2)...
CREATE TABLE JOB1
(
   JOB_ID VARCHAR(30),
   JOB_TITLE VARCHAR(30),
   MIN_SAL INT,
   MAX_SAL INT
);

INSERT INTO JOB1(JOB_ID, JOB_TITLE, MIN_SAL, MAX_SAL)
VALUES ('IT_PROG', 'PROGRAMMER', '4000', '10000')

INSERT INTO JOB1(JOB_ID, JOB_TITLE, MIN_SAL, MAX_SAL)
VALUES ('MK_MGR', 'MARKETING MANAGER', '9000', '15000')

INSERT INTO JOB1(JOB_ID, JOB_TITLE, MIN_SAL, MAX_SAL)
VALUES ('FI_MGR', 'FINANCE MANAGER', '8200', '12000')

INSERT INTO JOB1(JOB_ID, JOB_TITLE, MIN_SAL, MAX_SAL)
VALUES ('FI_ACC', 'ACCOU NT', '4200', '9000')

INSERT INTO JOB1(JOB_ID, JOB_TITLE, MIN_SAL, MAX_SAL)
VALUES ('LEC', 'LECTURE', '6000', '17000')

INSERT INTO JOB1(JOB_ID, JOB_TITLE, MIN_SAL, MAX_SAL)
VALUES ('COMP_OP', 'COMPUTER OPERATOR', '1500', '3000')

SELECT * FROM JOB1

UPDATE JOB1 SET JOB_TITLE = 'BIG DATA ANALYTICS' WHERE JOB_ID = 'FI_MGR';

DELETE FROM JOB1 WHERE MIN_SAL = '1500';