CREATE TABLE MASTER
(
   M_ID INT PRIMARY KEY,
   M_NAME NVARCHAR(10),
   M_PASSWORD NVARCHAR(30),
   M_ROLES NVARCHAR(15),
   M_EMAIL NVARCHAR(100)
);

INSERT INTO MASTER(M_ID, M_NAME, M_PASSWORD, M_ROLES, M_EMAIL)
VALUES('101', 'ROHIL0', '123456', 'ADMIN', 'ROHIL0@GMAIL.COM')
INSERT INTO MASTER(M_ID, M_NAME, M_PASSWORD, M_ROLES, M_EMAIL)
VALUES('102', 'ROHIL1', 'ABCDEFG', 'USER', 'ROHIL1@GMAIL.COM')
INSERT INTO MASTER(M_ID, M_NAME, M_PASSWORD, M_ROLES, M_EMAIL)
VALUES('103', 'ROHIL2', 'PQR123', 'SUPERADMIN', 'ROHIL2@GMAIL.COM')
INSERT INTO MASTER(M_ID, M_NAME, M_PASSWORD, M_ROLES, M_EMAIL)
VALUES('104', 'ROHIL3', '123PQR', 'ADMIN', 'ROHIL3@GMAIL.COM')
INSERT INTO MASTER(M_ID, M_NAME, M_PASSWORD, M_ROLES, M_EMAIL)
VALUES('105', 'ROHIL4', 'PQRLMN', 'USER', 'ROHIL4@GMAIL.COM')

SELECT * FROM MASTER;

rohilEntities