-->1)..
CREATE TABLE HOLIDAYS
(
   H_NAME VARCHAR(20) PRIMARY KEY,
   H_DAY VARCHAR(10),
   H_DATE DATE
);

INSERT INTO HOLIDAYS (H_NAME,H_DAY,H_DATE)
VALUES ('MAKAR SANKRANTI' , 'FRIDAY', '14-JAN-2022')

INSERT INTO HOLIDAYS (H_NAME,H_DAY,H_DATE)
VALUES ('REPUBLIC DAY' , 'WEDNESDAY', '26-JAN-2022')

INSERT INTO HOLIDAYS (H_NAME,H_DAY,H_DATE)
VALUES ('MAHA SHIVRATRI' , 'TUESDAY', '1-MAR-2022')

INSERT INTO HOLIDAYS (H_NAME,H_DAY,H_DATE)
VALUES ('HOLI' , 'FRIDAY', '18-MAR-2022')

INSERT INTO HOLIDAYS (H_NAME,H_DAY,H_DATE)
VALUES ('RAM NAVAMI' , 'SUNDAY', '10-APRIL-2022')

INSERT INTO HOLIDAYS (H_NAME,H_DAY,H_DATE)
VALUES ('AMBEDKAR JAYANTI' , 'THURSDAY', '14-APRIL-2022')

INSERT INTO HOLIDAYS (H_NAME,H_DAY,H_DATE)
VALUES ('GOOD FRIDAY' , 'FRIDAY', '15-APRIL-2022')

INSERT INTO HOLIDAYS (H_NAME,H_DAY,H_DATE)
VALUES ('EID-AL-FITR' , 'TUESDAY', '03-MAY-2022')

INSERT INTO HOLIDAYS (H_NAME,H_DAY,H_DATE)
VALUES ('RAKSHA BANDHAN' , 'THUESDAY', '11-AUG-2022')

INSERT INTO HOLIDAYS (H_NAME,H_DAY,H_DATE)
VALUES ('INDEPENDENCE DAY' , 'MONDAY', '15-AUG-2022')

INSERT INTO HOLIDAYS (H_NAME,H_DAY,H_DATE)
VALUES ('JANMASHTMI' , 'FRIDAY', '19-AUG-2022')

INSERT INTO HOLIDAYS (H_NAME,H_DAY,H_DATE)
VALUES ('GANDHI JAYANTI' , 'SUNDAY', '02-OCT-2022')

INSERT INTO HOLIDAYS (H_NAME,H_DAY,H_DATE)
VALUES ('DUSHHERA' , 'WEDNESDAY', '05-AUG-2022')

SELECT * FROM HOLIDAYS

--> 2)...
CREATE TABLE ATTENDENCE1
(
   ATT_ID INT PRIMARY KEY,
   EMP_ID INT,
   ATT_DATE DATE,
   ATT_TIME TIME
);

INSERT INTO ATTENDENCE1 (ATT_ID, EMP_ID, ATT_DATE, ATT_TIME)
VALUES ('12', '5', '2017-09-13', '09:54:00:000');

INSERT INTO ATTENDENCE1 (ATT_ID, EMP_ID, ATT_DATE, ATT_TIME)
VALUES ('13', '5', '2018-09-13', '18:39:00:000');

INSERT INTO ATTENDENCE1 (ATT_ID, EMP_ID, ATT_DATE, ATT_TIME)
VALUES ('11', '1', '2018-09-02', '11:34:00:000');

INSERT INTO ATTENDENCE1 (ATT_ID, EMP_ID, ATT_DATE, ATT_TIME)
VALUES ('9', '1', '2018-09-02', '18:13:00:000');

INSERT INTO ATTENDENCE1 (ATT_ID, EMP_ID, ATT_DATE, ATT_TIME)
VALUES ('5', '1', '2018-01-31', '10:00:00:000');

INSERT INTO ATTENDENCE1 (ATT_ID, EMP_ID, ATT_DATE, ATT_TIME)
VALUES ('4', '1', '2018-01-31', '14:02:00:000');

INSERT INTO ATTENDENCE1 (ATT_ID, EMP_ID, ATT_DATE, ATT_TIME)
VALUES ('14', '2', '2018-02-01', '10:10:00:000');

INSERT INTO ATTENDENCE1 (ATT_ID, EMP_ID, ATT_DATE, ATT_TIME)
VALUES ('7', '2', '2018-02-01', '17:41:00:000');

SELECT * FROM ATTENDENCE1

--> 3)..
CREATE TABLE SALARY1
(
   EMP_NO INT PRIMARY KEY,
   SALARY INT,
   E_NAME VARCHAR(10),
   MANAGER_ID INT
);

INSERT INTO SALARY1 (EMP_NO, SALARY, E_NAME, MANAGER_ID)
VALUES('4', '5555', 'ROHIL', '10')

INSERT INTO SALARY1 (EMP_NO, SALARY, E_NAME, MANAGER_ID)
VALUES('5', '40000', 'SMIT', '2')

INSERT INTO SALARY1 (EMP_NO, SALARY, E_NAME, MANAGER_ID)
VALUES('6', '8560', 'RAHIL', '2')

INSERT INTO SALARY1 (EMP_NO, SALARY, E_NAME, MANAGER_ID)
VALUES('2', '20000', 'VARSHIL', '20')

INSERT INTO SALARY1 (EMP_NO, SALARY, E_NAME, MANAGER_ID)
VALUES('1', '28000', 'DHRUVA;', '3')

INSERT INTO SALARY1 (EMP_NO, SALARY, E_NAME, MANAGER_ID)
VALUES('9', '5900', 'DIVY', '6')

SELECT * FROM SALARY1

-->4)...
CREATE TABLE CUSTOMERS(
   CUSTOMERID INT PRIMARY KEY,
   CUSTOMERNAME VARCHAR(40),
   CONTACTNAME VARCHAR(20),
   ADDRESS VARCHAR(100),
   CITY VARCHAR(9),
   POSTALCODE INT,
   COUNTRY VARCHAR(30)
);

INSERT INTO CUSTOMERS(CUSTOMERID, CUSTOMERNAME, CONTACTNAME, ADDRESS, CITY, POSTALCODE, COUNTRY)
VALUES('1', 'AAKASH', 'MARIA ANDERS', 'XYZ', 'BERLIN', '12209', 'GERMANY')

INSERT INTO CUSTOMERS(CUSTOMERID, CUSTOMERNAME, CONTACTNAME, ADDRESS, CITY, POSTALCODE, COUNTRY)
VALUES('2', 'HARDIK', 'ANA TRUJILLO', 'ABC', 'MEXICO', '05021', 'MEXICO')

INSERT INTO CUSTOMERS(CUSTOMERID, CUSTOMERNAME, CONTACTNAME, ADDRESS, CITY, POSTALCODE, COUNTRY)
VALUES('3', 'SACHIB', 'ANTONIO MORENO', 'PQR', 'MEXICO', '12209', 'MEXICO')

SELECT * FROM CUSTOMERS

--> 5)...
CREATE TABLE SUPPLIERS(
  SUPPLIERID INT PRIMARY KEY,
  SUPPLIERNAME VARCHAR(10),
  CONTACTNAME VARCHAR(20),
  ADDRESS VARCHAR(200),
  CITY VARCHAR(10),
  POSTALCODE INT,
  COUNTRY VARCHAR(5)
);
INSERT INTO SUPPLIERS(SUPPLIERID,SUPPLIERNAME,CONTACTNAME,ADDRESS,CITY,POSTALCODE,COUNTRY)
VALUES('1', 'RAJESH', 'CHARLOTTE COOPER', 'LMN', 'LONDONA', '12345','UK')

INSERT INTO SUPPLIERS(SUPPLIERID,SUPPLIERNAME,CONTACTNAME,ADDRESS,CITY,POSTALCODE,COUNTRY)
VALUES('2', 'AMIT', 'SHELLEY BURKE', 'QET', 'NEWORLEANS', '70117','USA')

INSERT INTO SUPPLIERS(SUPPLIERID,SUPPLIERNAME,CONTACTNAME,ADDRESS,CITY,POSTALCODE,COUNTRY)
VALUES('3', 'HET', 'REGINA MURPHY', 'ADG', 'ANNARBOR', '48104','USA')

SELECT * FROM SUPPLIERS

--->TRANSFER ONE TABLE DATA TO ANOTHER TABLE:

SELECT * INTO ROHIL FROM CUSTOMERS
SELECT * FROM ROHIL;

SELECT * INTO ROHILO FROM SUPPLIERS
SELECT * FROM ROHILO;

---> NATURAL JOIN:
SELECT SUPPLIERNAME FROM CUSTOMERS NATURAL JOIN SUPPLIERS WHERE CUSTOMERID=SUPPLIERID;
SELECT * FROM CUSTOMERS NATURAL JOIN SUPPLIERS; 

--> INNER JOIN:
SELECT SUPPLIERNAME, CUSTOMERNAME, CUSTOMERS.CITY FROM CUSTOMERS INNER JOIN SUPPLIERS ON CUSTOMERID=SUPPLIERID;

--->LEFT OUTER JOIN:
SELECT CUSTOMERNAME, SUPPLIERS.CITY, CUSTOMERS.COUNTRY, CUSTOMERS.CONTACTNAME, SUPPLIERS.CONTACTNAME FROM CUSTOMERS LEFT JOIN SUPPLIERS ON CUSTOMERID=SUPPLIERID;

-->RIGHT OUTER JOIN:
SELECT CUSTOMERNAME, SUPPLIERS.CITY, CUSTOMERS.COUNTRY, CUSTOMERS.CONTACTNAME, SUPPLIERS.CONTACTNAME FROM CUSTOMERS RIGHT JOIN SUPPLIERS ON CUSTOMERID=SUPPLIERID;

-->GROUP BY:
SELECT SUPPLIERNAME,ADDRESS, SUM(POSTALCODE) AS TOTALCODE, COUNT(SUPPLIERID) AS TOTALSUPPLER FROM SUPPLIERS WHERE CITY='LONDONA' GROUP BY SUPPLIERNAME,ADDRESS