//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordForgotDairy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dairy4
    {
        public int DairyId { get; set; }
        public string Name { get; set; }
        public string MobileNo { get; set; }
        public string DairyNumber { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Taluka { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public Nullable<int> MobileId { get; set; }
        public Nullable<bool> SyncState { get; set; }
        public Nullable<int> DealerId { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> LastSyncDate { get; set; }
        public string DeviceId { get; set; }
        public string FCMToken { get; set; }
        public string DeviceModel { get; set; }
        public string DeviceCompany { get; set; }
        public string AndroidVersion { get; set; }
        public Nullable<int> Refferalld { get; set; }
        public Nullable<decimal> ReferralAmount { get; set; }
        public Nullable<decimal> WithdrawAmount { get; set; }
        public Nullable<bool> IsSubscribe { get; set; }
    }
}
