//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subscriptiondairy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DairySubscription
    {
        public int DairySubscriptionId { get; set; }
        public Nullable<int> SubscriptionId { get; set; }
        public Nullable<int> DairyId { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public string PaidAmount { get; set; }
        public string SubscriptionPrice { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<int> MobileId { get; set; }
        public Nullable<bool> SyncState { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> CreatedIP { get; set; }
        public Nullable<int> UpdatedIP { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
