//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milk_Dairy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dairy
    {
        public int DairyId { get; set; }
        public string Name { get; set; }
        public string MobileNo { get; set; }
        public string DairyNumber { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Taluka { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public int MobileId { get; set; }
        public bool SyncState { get; set; }
        public int Dealerld { get; set; }
        public string Password { get; set; }
        public System.DateTime LastSyncDate { get; set; }
        public string DeviceId { get; set; }
        public string FCMToken { get; set; }
        public string DeviceModel { get; set; }
        public string DeviceCompany { get; set; }
        public string AndroidVersion { get; set; }
        public int Refferalld { get; set; }
        public decimal ReferralAmount { get; set; }
        public decimal WithdrawAmount { get; set; }
        public bool IsSubscribe { get; set; }
    }
}
