//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milk_Dairy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrintAndMessageSetting
    {
        public int PrintSettingId { get; set; }
        public Nullable<int> DairyId { get; set; }
        public string PrintMethod { get; set; }
        public Nullable<bool> PrintBoldFont { get; set; }
        public Nullable<bool> PaymentRoundOfff { get; set; }
        public Nullable<bool> TranslateEverything { get; set; }
        public Nullable<bool> ShowLink { get; set; }
        public Nullable<bool> ShowSNFCLR { get; set; }
        public Nullable<bool> ShowRSLTR { get; set; }
        public Nullable<bool> ShowKGFAT { get; set; }
        public string SMSMethod { get; set; }
        public Nullable<int> MobileId { get; set; }
        public Nullable<bool> SyncState { get; set; }
        public Nullable<bool> Active { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> CreatedIp { get; set; }
        public Nullable<int> UpdatedIp { get; set; }
    }
}
